import type { Quote } from "./types";

export const quotes: Quote[] = [
  { text: "The only truth is music.", author: "Jack Kerouac" },
  { text: "Music is the shorthand of emotion.", author: "Leo Tolstoy" },
  { text: "After silence, that which comes nearest to expressing the inexpressible is music.", author: "Aldous Huxley" },
  { text: "Music expresses that which cannot be said and on which it is impossible to be silent.", author: "Victor Hugo" },
  { text: "Where words fail, music speaks.", author: "Hans Christian Andersen" },
  { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
  { text: "Music is the wine that fills the cup of silence.", author: "Robert Fripp" },
  { text: "One good thing about music, when it hits you, you feel no pain.", author: "Bob Marley" },
  { text: "Music is the moonlight in the gloomy night of life.", author: "Jean Paul" },
  { text: "If music be the food of love, play on.", author: "William Shakespeare" },
  { text: "I think music in itself is healing.", author: "Billy Joel" },
  { text: "Music is a world within itself, with a language we all understand.", author: "Stevie Wonder" },
  { text: "Music washes away from the soul the dust of everyday life.", author: "Berthold Auerbach" },
  { text: "The music is not in the notes, but in the silence between.", author: "Wolfgang Amadeus Mozart" },
  { text: "Life is for the living. Death is for the dead. Let life be like music. And death a note unsaid.", author: "Langston Hughes" },
  { text: "Music is the literature of the heart; it commences where speech ends.", author: "Alphonse de Lamartine" },
  { text: "People haven't always been there for me but music always has.", author: "Taylor Swift" },
  { text: "Music is enough for a lifetime, but a lifetime is not enough for music.", author: "Sergei Rachmaninoff" },
  { text: "There is no feeling, except the extremes of fear and grief, that does not find relief in music.", author: "George Eliot" },
  { text: "Music is what tell us that the human race is greater than we realize.", author: "Napoleon Bonaparte" },
  { text: "And those who were seen dancing were thought to be insane by those who could not hear the music.", author: "Friedrich Nietzsche" },
  { text: "To stop the flow of music would be like the stopping of time itself, incredible and inconceivable.", author: "Aaron Copland" },
  { text: "Music gives a soul to the universe, wings to the mind, flight to the imagination and life to everything.", author: "Plato" },
  { text: "When you hear music, after it's over, it's gone in the air. You can never capture it again.", author: "Eric Dolphy" },
  { text: "The earth has music for those who listen.", author: "William Shakespeare" },
  { text: "If I were not a physicist, I would probably be a musician.", author: "Albert Einstein" },
  { text: "Music is the great uniter. An incredible force.", author: "Leonard Cohen" },
  { text: "I was born with music inside me. Music was one of my parts.", author: "Ray Charles" },
  { text: "Music is the universal language of mankind.", author: "Henry Wadsworth Longfellow" },
  { text: "We are the music-makers, and we are the dreamers of dreams.", author: "Arthur O'Shaughnessy" },
  { text: "Music is your own experience, your own thoughts, your wisdom.", author: "Charlie Parker" },
  { text: "Everything in the universe has a rhythm, everything dances.", author: "Maya Angelou" },
  { text: "Music is the strongest form of magic.", author: "Marilyn Manson" },
  { text: "If you want to find the secrets of the universe, think in terms of energy, frequency and vibration.", author: "Nikola Tesla" },
  { text: "There are two means of refuge from the miseries of life: music and cats.", author: "Albert Schweitzer" },
  { text: "Music in the soul can be heard by the universe.", author: "Lao Tzu" },
  { text: "I see my life in terms of music.", author: "Albert Einstein" },
  { text: "Music acts like a magic key, to which the most tightly closed heart opens.", author: "Maria von Trapp" },
  { text: "Jazz is not just music, it's a way of life, it's a way of being, a way of thinking.", author: "Nina Simone" },
  { text: "Take a music bath once or twice a week for a few seasons. You will find it is to the soul what a water bath is to the body.", author: "Oliver Wendell Holmes" },
  { text: "Ah, music. A magic beyond all we do here.", author: "J.K. Rowling" },
  { text: "Music is the art which is most nigh to tears and memories.", author: "Oscar Wilde" },
  { text: "Music is perpetual, and only the hearing is intermittent.", author: "Henry David Thoreau" },
  { text: "A painter paints pictures on canvas. But musicians paint their pictures on silence.", author: "Leopold Stokowski" },
  { text: "The times you lived through, the people you shared those times with — nothing brings it all to life like an old song.", author: "Haruki Murakami" },
  { text: "Music is the divine way to tell beautiful, poetic things to the heart.", author: "Pablo Casals" },
  { text: "You can cage the singer but not the song.", author: "Harry Belafonte" },
  { text: "Every song has a memory; every song has the ability to make or break your heart, shut down the world, or open it up.", author: "Patti Smith" },
  { text: "There's a basic rule which runs through all kinds of music, kind of an unwritten rule. I don't know what it is, but I've got it.", author: "Ron Wood" },
  { text: "Music should strike fire from the heart of man, and bring tears from the eyes of woman.", author: "Ludwig van Beethoven" },
  { text: "I don't sing because I'm happy; I'm happy because I sing.", author: "William James" },
  { text: "What is a poet? An unhappy person who conceals profound anguish in his heart but whose lips are so formed that as sighs and cries pass over them they sound like beautiful music.", author: "Soren Kierkegaard" },
  { text: "Who hears music, feels his solitude peopled at once.", author: "Robert Browning" },
  { text: "If I should ever die, God forbid, let this be my epitaph: The only proof he needed for the existence of God was music.", author: "Kurt Vonnegut" },
  { text: "Songs are as sad as the listener.", author: "Jonathan Safran Foer" },
  { text: "All you need is love. But a little chocolate now and then doesn't hurt.", author: "Charles M. Schulz" },
  { text: "My heart, which is so full to overflowing, has often been solaced and refreshed by music when sick and weary.", author: "Martin Luther" },
  { text: "The wise musicians are those who play what they can master.", author: "Duke Ellington" },
  { text: "Do you know that our soul is composed of harmony?", author: "Leonardo da Vinci" },
  { text: "Let me be surrounded by music, always, and die quietly.", author: "Rumi" },
];
